package ru.nsu.ccfit.factory.config;

public enum Parameter {
    ACCESSORY_SUPPLIERS_NUMBER,
    DEALERS_NUMBER,
    WORKERS_NUMBER,
    ACCESSORY_SUPPLY_SPEED,
    BODY_SUPPLY_SPEED,
    ENGINE_SUPPLY_SPEED,
    AUTO_SUPPLY_SPEED,
    ACCESSORY_STORAGE_LIMIT,
    BODY_STORAGE_LIMIT,
    ENGINE_STORAGE_LIMIT,
    AUTO_STORAGE_LIMIT
}
